### ISSUE TITLE
Noticing an EoL war lets create a treaty

### ISSUE THREAD

**Issue by Elaniobro** [newyorkmyc/keys-typeahead#13]
There are certainly discrepancies between your (@mrozanoff) IDE and mine. This is causing undue code review fatigue, b/c its highlighting the changes in the code that are not really "changes"

Lets set up an [Editor Config](https://editorconfig.org/) dot file in the repo to resolve the discrepancy.

**Comment by mrozanoff** [comment]
what are the discrepancies besides npm and pnpm?

**Comment by Elaniobro** [comment]
[Here is an example](https://github.com/newyorkmyc/keys-typeahead/pull/7/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L15), where the space at the EOL is removed which becomes part of the undue burden of a review for a PR

**Comment by Elaniobro** [comment]
pnpm causes less bloat b/c it symlinks to a central drive on the hardisk. Its been awhile since I really developed, so its very likely that the bloat issue with npm was resolved if you are using v3. More info may be found on [pnpm vs npm](https://pnpm.io/pnpm-vs-npm)
