### ISSUE TITLE
Make Python Script Build Phylum Mycetozoa

### ISSUE THREAD

**Issue by mrozanoff** [newyorkmyc/keys-typeahead#9]
Have to figure out how to add only the phylum in addition to the rest of the data model. I think I can build the preset json out more, with the top taxon being life, then having the normal fungi, then having a separate branch going straight from Protist to Mycetozoa

**Comment by Elaniobro** [comment]
Dope! I think we can restrict it to just Myxomycetes Class, we don't nee the Phylum or Kingdom, hopefully that reduces the load a bit.
